version: "2"

linters:
  enable:
    - bodyclose
    - ineffassign
    - unparam
    - prealloc
    - govet
    - staticcheck
    - errcheck
    - nilerr
    - gosec
    - sqlclosecheck
    - forcetypeassert
    - revive
    - gocritic
    - mnd
    - misspell
    - dupl
    - cyclop
    - nestif
    - goconst
    - goprintffuncname

formatters:
  enable:
    - gofmt
