/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as GenerateClientRouteImport } from './routes/generate-client'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentsAgentIdRouteImport } from './routes/agents.$agentId'
import { Route as AgentsAgentIdIndexRouteImport } from './routes/agents.$agentId/index'
import { Route as AgentsAgentIdTerminalRouteImport } from './routes/agents.$agentId/terminal'
import { Route as AgentsAgentIdSystemRouteImport } from './routes/agents.$agentId/system'
import { Route as AgentsAgentIdScreenRouteImport } from './routes/agents.$agentId/screen'
import { Route as AgentsAgentIdLogsRouteImport } from './routes/agents.$agentId/logs'
import { Route as AgentsAgentIdFilesRouteImport } from './routes/agents.$agentId/files'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateClientRoute = GenerateClientRouteImport.update({
  id: '/generate-client',
  path: '/generate-client',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsAgentIdRoute = AgentsAgentIdRouteImport.update({
  id: '/agents/$agentId',
  path: '/agents/$agentId',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsAgentIdIndexRoute = AgentsAgentIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AgentsAgentIdRoute,
} as any)
const AgentsAgentIdTerminalRoute = AgentsAgentIdTerminalRouteImport.update({
  id: '/terminal',
  path: '/terminal',
  getParentRoute: () => AgentsAgentIdRoute,
} as any)
const AgentsAgentIdSystemRoute = AgentsAgentIdSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => AgentsAgentIdRoute,
} as any)
const AgentsAgentIdScreenRoute = AgentsAgentIdScreenRouteImport.update({
  id: '/screen',
  path: '/screen',
  getParentRoute: () => AgentsAgentIdRoute,
} as any)
const AgentsAgentIdLogsRoute = AgentsAgentIdLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AgentsAgentIdRoute,
} as any)
const AgentsAgentIdFilesRoute = AgentsAgentIdFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => AgentsAgentIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/generate-client': typeof GenerateClientRoute
  '/terms': typeof TermsRoute
  '/agents/$agentId': typeof AgentsAgentIdRouteWithChildren
  '/agents/$agentId/files': typeof AgentsAgentIdFilesRoute
  '/agents/$agentId/logs': typeof AgentsAgentIdLogsRoute
  '/agents/$agentId/screen': typeof AgentsAgentIdScreenRoute
  '/agents/$agentId/system': typeof AgentsAgentIdSystemRoute
  '/agents/$agentId/terminal': typeof AgentsAgentIdTerminalRoute
  '/agents/$agentId/': typeof AgentsAgentIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/generate-client': typeof GenerateClientRoute
  '/terms': typeof TermsRoute
  '/agents/$agentId/files': typeof AgentsAgentIdFilesRoute
  '/agents/$agentId/logs': typeof AgentsAgentIdLogsRoute
  '/agents/$agentId/screen': typeof AgentsAgentIdScreenRoute
  '/agents/$agentId/system': typeof AgentsAgentIdSystemRoute
  '/agents/$agentId/terminal': typeof AgentsAgentIdTerminalRoute
  '/agents/$agentId': typeof AgentsAgentIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/generate-client': typeof GenerateClientRoute
  '/terms': typeof TermsRoute
  '/agents/$agentId': typeof AgentsAgentIdRouteWithChildren
  '/agents/$agentId/files': typeof AgentsAgentIdFilesRoute
  '/agents/$agentId/logs': typeof AgentsAgentIdLogsRoute
  '/agents/$agentId/screen': typeof AgentsAgentIdScreenRoute
  '/agents/$agentId/system': typeof AgentsAgentIdSystemRoute
  '/agents/$agentId/terminal': typeof AgentsAgentIdTerminalRoute
  '/agents/$agentId/': typeof AgentsAgentIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/generate-client'
    | '/terms'
    | '/agents/$agentId'
    | '/agents/$agentId/files'
    | '/agents/$agentId/logs'
    | '/agents/$agentId/screen'
    | '/agents/$agentId/system'
    | '/agents/$agentId/terminal'
    | '/agents/$agentId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/generate-client'
    | '/terms'
    | '/agents/$agentId/files'
    | '/agents/$agentId/logs'
    | '/agents/$agentId/screen'
    | '/agents/$agentId/system'
    | '/agents/$agentId/terminal'
    | '/agents/$agentId'
  id:
    | '__root__'
    | '/'
    | '/generate-client'
    | '/terms'
    | '/agents/$agentId'
    | '/agents/$agentId/files'
    | '/agents/$agentId/logs'
    | '/agents/$agentId/screen'
    | '/agents/$agentId/system'
    | '/agents/$agentId/terminal'
    | '/agents/$agentId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GenerateClientRoute: typeof GenerateClientRoute
  TermsRoute: typeof TermsRoute
  AgentsAgentIdRoute: typeof AgentsAgentIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate-client': {
      id: '/generate-client'
      path: '/generate-client'
      fullPath: '/generate-client'
      preLoaderRoute: typeof GenerateClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$agentId': {
      id: '/agents/$agentId'
      path: '/agents/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AgentsAgentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$agentId/': {
      id: '/agents/$agentId/'
      path: '/'
      fullPath: '/agents/$agentId/'
      preLoaderRoute: typeof AgentsAgentIdIndexRouteImport
      parentRoute: typeof AgentsAgentIdRoute
    }
    '/agents/$agentId/terminal': {
      id: '/agents/$agentId/terminal'
      path: '/terminal'
      fullPath: '/agents/$agentId/terminal'
      preLoaderRoute: typeof AgentsAgentIdTerminalRouteImport
      parentRoute: typeof AgentsAgentIdRoute
    }
    '/agents/$agentId/system': {
      id: '/agents/$agentId/system'
      path: '/system'
      fullPath: '/agents/$agentId/system'
      preLoaderRoute: typeof AgentsAgentIdSystemRouteImport
      parentRoute: typeof AgentsAgentIdRoute
    }
    '/agents/$agentId/screen': {
      id: '/agents/$agentId/screen'
      path: '/screen'
      fullPath: '/agents/$agentId/screen'
      preLoaderRoute: typeof AgentsAgentIdScreenRouteImport
      parentRoute: typeof AgentsAgentIdRoute
    }
    '/agents/$agentId/logs': {
      id: '/agents/$agentId/logs'
      path: '/logs'
      fullPath: '/agents/$agentId/logs'
      preLoaderRoute: typeof AgentsAgentIdLogsRouteImport
      parentRoute: typeof AgentsAgentIdRoute
    }
    '/agents/$agentId/files': {
      id: '/agents/$agentId/files'
      path: '/files'
      fullPath: '/agents/$agentId/files'
      preLoaderRoute: typeof AgentsAgentIdFilesRouteImport
      parentRoute: typeof AgentsAgentIdRoute
    }
  }
}

interface AgentsAgentIdRouteChildren {
  AgentsAgentIdFilesRoute: typeof AgentsAgentIdFilesRoute
  AgentsAgentIdLogsRoute: typeof AgentsAgentIdLogsRoute
  AgentsAgentIdScreenRoute: typeof AgentsAgentIdScreenRoute
  AgentsAgentIdSystemRoute: typeof AgentsAgentIdSystemRoute
  AgentsAgentIdTerminalRoute: typeof AgentsAgentIdTerminalRoute
  AgentsAgentIdIndexRoute: typeof AgentsAgentIdIndexRoute
}

const AgentsAgentIdRouteChildren: AgentsAgentIdRouteChildren = {
  AgentsAgentIdFilesRoute: AgentsAgentIdFilesRoute,
  AgentsAgentIdLogsRoute: AgentsAgentIdLogsRoute,
  AgentsAgentIdScreenRoute: AgentsAgentIdScreenRoute,
  AgentsAgentIdSystemRoute: AgentsAgentIdSystemRoute,
  AgentsAgentIdTerminalRoute: AgentsAgentIdTerminalRoute,
  AgentsAgentIdIndexRoute: AgentsAgentIdIndexRoute,
}

const AgentsAgentIdRouteWithChildren = AgentsAgentIdRoute._addFileChildren(
  AgentsAgentIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GenerateClientRoute: GenerateClientRoute,
  TermsRoute: TermsRoute,
  AgentsAgentIdRoute: AgentsAgentIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
