//go:build !development

// Code generated by the gateway artifact builder. DO NOT EDIT.

package config

// generatedConfig intentionally contains no defaults. The gateway artifact
// builder replaces this file in its isolated workspace before production build.
// A binary built without generation must fail closed during startup.
func generatedConfig() Config {
	return Config{}
}
