// Code generated by go run ./cmd/wiregen; DO NOT EDIT.

package wire

// ClientHello is the canonical revision 1 body for MessageClientHello.
type ClientHello struct {
	MinimumMinor          uint64
	MaximumMinor          uint64
	Features              uint64
	ImplementationVersion string
	Platform              uint64
	Architecture          uint64
	ClientInstanceNonce   [16]byte
}

// MarshalBinary returns the canonical bounded ClientHello body.
func (message ClientHello) MarshalBinary() ([]byte, error) {
	builder := NewBuilder(256)
	builder.BoundedUint(message.MinimumMinor, 65535)
	builder.BoundedUint(message.MaximumMinor, 65535)
	builder.BoundedUint(message.Features, 18446744073709551615)
	builder.String(message.ImplementationVersion, 64)
	builder.BoundedUint(message.Platform, 3)
	builder.BoundedUint(message.Architecture, 2)
	builder.Fixed16(message.ClientInstanceNonce)
	return builder.Bytes()
}

// UnmarshalBinary replaces the message with one exact canonical ClientHello body.
func (message *ClientHello) UnmarshalBinary(body []byte) error {
	parser := NewParser(body)
	var decoded ClientHello
	decoded.MinimumMinor = parser.Uint(65535)
	decoded.MaximumMinor = parser.Uint(65535)
	decoded.Features = parser.Uint(18446744073709551615)
	decoded.ImplementationVersion = parser.String(64)
	decoded.Platform = parser.Uint(3)
	decoded.Architecture = parser.Uint(2)
	decoded.ClientInstanceNonce = parser.Fixed16()
	if err := parser.Done(); err != nil {
		return err
	}
	*message = decoded
	return nil
}

// ServerHello is the canonical revision 1 body for MessageServerHello.
type ServerHello struct {
	SelectedMinor                 uint64
	NegotiatedFeatures            uint64
	SessionID                     [16]byte
	HeartbeatIntervalMilliseconds uint64
	MaximumIdleMilliseconds       uint64
	EventFrameMaximum             uint64
	ConcurrentTransferStreams     uint64
	CommandVerificationKeyID      string
}

// MarshalBinary returns the canonical bounded ServerHello body.
func (message ServerHello) MarshalBinary() ([]byte, error) {
	builder := NewBuilder(256)
	builder.BoundedUint(message.SelectedMinor, 65535)
	builder.BoundedUint(message.NegotiatedFeatures, 18446744073709551615)
	builder.Fixed16(message.SessionID)
	builder.BoundedUint(message.HeartbeatIntervalMilliseconds, 300000)
	builder.BoundedUint(message.MaximumIdleMilliseconds, 3600000)
	builder.BoundedUint(message.EventFrameMaximum, 16777216)
	builder.BoundedUint(message.ConcurrentTransferStreams, 64)
	builder.String(message.CommandVerificationKeyID, 128)
	return builder.Bytes()
}

// UnmarshalBinary replaces the message with one exact canonical ServerHello body.
func (message *ServerHello) UnmarshalBinary(body []byte) error {
	parser := NewParser(body)
	var decoded ServerHello
	decoded.SelectedMinor = parser.Uint(65535)
	decoded.NegotiatedFeatures = parser.Uint(18446744073709551615)
	decoded.SessionID = parser.Fixed16()
	decoded.HeartbeatIntervalMilliseconds = parser.Uint(300000)
	decoded.MaximumIdleMilliseconds = parser.Uint(3600000)
	decoded.EventFrameMaximum = parser.Uint(16777216)
	decoded.ConcurrentTransferStreams = parser.Uint(64)
	decoded.CommandVerificationKeyID = parser.String(128)
	if err := parser.Done(); err != nil {
		return err
	}
	*message = decoded
	return nil
}

// Ping is the canonical revision 1 body for MessagePing.
type Ping struct {
	Nonce uint64
}

// MarshalBinary returns the canonical bounded Ping body.
func (message Ping) MarshalBinary() ([]byte, error) {
	builder := NewBuilder(256)
	builder.BoundedUint(message.Nonce, 18446744073709551615)
	return builder.Bytes()
}

// UnmarshalBinary replaces the message with one exact canonical Ping body.
func (message *Ping) UnmarshalBinary(body []byte) error {
	parser := NewParser(body)
	var decoded Ping
	decoded.Nonce = parser.Uint(18446744073709551615)
	if err := parser.Done(); err != nil {
		return err
	}
	*message = decoded
	return nil
}

// Pong is the canonical revision 1 body for MessagePong.
type Pong struct {
	Nonce uint64
}

// MarshalBinary returns the canonical bounded Pong body.
func (message Pong) MarshalBinary() ([]byte, error) {
	builder := NewBuilder(256)
	builder.BoundedUint(message.Nonce, 18446744073709551615)
	return builder.Bytes()
}

// UnmarshalBinary replaces the message with one exact canonical Pong body.
func (message *Pong) UnmarshalBinary(body []byte) error {
	parser := NewParser(body)
	var decoded Pong
	decoded.Nonce = parser.Uint(18446744073709551615)
	if err := parser.Done(); err != nil {
		return err
	}
	*message = decoded
	return nil
}

// MessageAck is the canonical revision 1 body for MessageMessageAck.
type MessageAck struct {
	// Presence selects assigned optional fields; unassigned bits are rejected.
	Presence         uint64
	OriginalSequence uint64
	Status           uint64
	Commit           uint64
	ReceiptID        [16]byte
	Retry            uint64
	PublicErrorCode  string
}

// MarshalBinary returns the canonical bounded MessageAck body.
func (message MessageAck) MarshalBinary() ([]byte, error) {
	builder := NewBuilder(256)
	builder.Presence(message.Presence, 2)
	builder.BoundedUint(message.OriginalSequence, 18446744073709551615)
	builder.BoundedUint(message.Status, 5)
	builder.BoundedUint(message.Commit, 5)
	if message.Presence&(uint64(1)<<0) != 0 {
		builder.Fixed16(message.ReceiptID)
	}
	builder.BoundedUint(message.Retry, 3)
	if message.Presence&(uint64(1)<<1) != 0 {
		builder.String(message.PublicErrorCode, 64)
	}
	return builder.Bytes()
}

// UnmarshalBinary replaces the message with one exact canonical MessageAck body.
func (message *MessageAck) UnmarshalBinary(body []byte) error {
	parser := NewParser(body)
	var decoded MessageAck
	decoded.Presence = parser.Presence(2)
	decoded.OriginalSequence = parser.Uint(18446744073709551615)
	decoded.Status = parser.Uint(5)
	decoded.Commit = parser.Uint(5)
	if decoded.Presence&(uint64(1)<<0) != 0 {
		decoded.ReceiptID = parser.Fixed16()
	}
	decoded.Retry = parser.Uint(3)
	if decoded.Presence&(uint64(1)<<1) != 0 {
		decoded.PublicErrorCode = parser.String(64)
	}
	if err := parser.Done(); err != nil {
		return err
	}
	*message = decoded
	return nil
}

// ProtocolError is the canonical revision 1 body for MessageProtocolError.
type ProtocolError struct {
	Scope           uint64
	Code            uint64
	PublicErrorCode string
}

// MarshalBinary returns the canonical bounded ProtocolError body.
func (message ProtocolError) MarshalBinary() ([]byte, error) {
	builder := NewBuilder(256)
	builder.BoundedUint(message.Scope, 3)
	builder.BoundedUint(message.Code, 511)
	builder.String(message.PublicErrorCode, 64)
	return builder.Bytes()
}

// UnmarshalBinary replaces the message with one exact canonical ProtocolError body.
func (message *ProtocolError) UnmarshalBinary(body []byte) error {
	parser := NewParser(body)
	var decoded ProtocolError
	decoded.Scope = parser.Uint(3)
	decoded.Code = parser.Uint(511)
	decoded.PublicErrorCode = parser.String(64)
	if err := parser.Done(); err != nil {
		return err
	}
	*message = decoded
	return nil
}

// Drain is the canonical revision 1 body for MessageDrain.
type Drain struct {
	DeadlineMilliseconds uint64
	Reason               uint64
}

// MarshalBinary returns the canonical bounded Drain body.
func (message Drain) MarshalBinary() ([]byte, error) {
	builder := NewBuilder(256)
	builder.BoundedUint(message.DeadlineMilliseconds, 300000)
	builder.BoundedUint(message.Reason, 16)
	return builder.Bytes()
}

// UnmarshalBinary replaces the message with one exact canonical Drain body.
func (message *Drain) UnmarshalBinary(body []byte) error {
	parser := NewParser(body)
	var decoded Drain
	decoded.DeadlineMilliseconds = parser.Uint(300000)
	decoded.Reason = parser.Uint(16)
	if err := parser.Done(); err != nil {
		return err
	}
	*message = decoded
	return nil
}

// SessionReplaced is the canonical revision 1 body for MessageSessionReplaced.
type SessionReplaced struct {
	ReplacementSessionID [16]byte
}

// MarshalBinary returns the canonical bounded SessionReplaced body.
func (message SessionReplaced) MarshalBinary() ([]byte, error) {
	builder := NewBuilder(256)
	builder.Fixed16(message.ReplacementSessionID)
	return builder.Bytes()
}

// UnmarshalBinary replaces the message with one exact canonical SessionReplaced body.
func (message *SessionReplaced) UnmarshalBinary(body []byte) error {
	parser := NewParser(body)
	var decoded SessionReplaced
	decoded.ReplacementSessionID = parser.Fixed16()
	if err := parser.Done(); err != nil {
		return err
	}
	*message = decoded
	return nil
}

// Heartbeat is the canonical revision 1 body for MessageHeartbeat.
type Heartbeat struct {
	// Presence selects assigned optional fields; unassigned bits are rejected.
	Presence              uint64
	Hostname              string
	OSVersion             string
	CPULoadPPM            uint64
	RAMUsagePPM           uint64
	UptimeSeconds         uint64
	CPUModel              string
	CPUCores              uint64
	CPUThreads            uint64
	TotalRAMBytes         uint64
	GPUDevices            []string
	NetworkName           string
	NetworkAddresses      []string
	KernelVersion         string
	CPUFrequencyMHz       uint64
	NetworkOnline         bool
	LinkSpeedMbps         uint64
	NetworkType           uint64
	TotalStorageBytes     uint64
	AvailableStorageBytes uint64
	NetworkSSID           string
	UsedStorageBytes      uint64
	StorageUsagePPM       uint64
	InodeUsagePPM         uint64
	StorageDevice         string
	StorageFilesystem     string
	StorageMountpoint     string
	StorageModel          string
	StorageType           uint64
	StorageReadOnly       bool
	ApplicationTypes      []ApplicationUsage
}

// MarshalBinary returns the canonical bounded Heartbeat body.
func (message Heartbeat) MarshalBinary() ([]byte, error) {
	builder := NewBuilder(256)
	builder.Presence(message.Presence, 29)
	builder.String(message.Hostname, 120)
	if message.Presence&(uint64(1)<<0) != 0 {
		builder.String(message.OSVersion, 120)
	}
	if message.Presence&(uint64(1)<<1) != 0 {
		builder.BoundedUint(message.CPULoadPPM, 1000000)
	}
	if message.Presence&(uint64(1)<<2) != 0 {
		builder.BoundedUint(message.RAMUsagePPM, 1000000)
	}
	if message.Presence&(uint64(1)<<3) != 0 {
		builder.BoundedUint(message.UptimeSeconds, 3155760000)
	}
	if message.Presence&(uint64(1)<<4) != 0 {
		builder.String(message.CPUModel, 160)
	}
	if message.Presence&(uint64(1)<<5) != 0 {
		builder.BoundedUint(message.CPUCores, 4096)
	}
	if message.Presence&(uint64(1)<<6) != 0 {
		builder.BoundedUint(message.CPUThreads, 8192)
	}
	if message.Presence&(uint64(1)<<7) != 0 {
		builder.BoundedUint(message.TotalRAMBytes, 18446744073709551615)
	}
	if message.Presence&(uint64(1)<<8) != 0 {
		builder.StringList(message.GPUDevices, 32, 160, 4096)
	}
	if message.Presence&(uint64(1)<<9) != 0 {
		builder.String(message.NetworkName, 120)
	}
	if message.Presence&(uint64(1)<<10) != 0 {
		builder.StringList(message.NetworkAddresses, 64, 64, 4096)
	}
	if message.Presence&(uint64(1)<<11) != 0 {
		builder.String(message.KernelVersion, 120)
	}
	if message.Presence&(uint64(1)<<12) != 0 {
		builder.BoundedUint(message.CPUFrequencyMHz, 1000000)
	}
	if message.Presence&(uint64(1)<<13) != 0 {
		builder.Bool(message.NetworkOnline)
	}
	if message.Presence&(uint64(1)<<14) != 0 {
		builder.BoundedUint(message.LinkSpeedMbps, 1000000000)
	}
	if message.Presence&(uint64(1)<<15) != 0 {
		builder.BoundedUint(message.NetworkType, 16)
	}
	if message.Presence&(uint64(1)<<16) != 0 {
		builder.BoundedUint(message.TotalStorageBytes, 18446744073709551615)
	}
	if message.Presence&(uint64(1)<<17) != 0 {
		builder.BoundedUint(message.AvailableStorageBytes, 18446744073709551615)
	}
	if message.Presence&(uint64(1)<<18) != 0 {
		builder.String(message.NetworkSSID, 128)
	}
	if message.Presence&(uint64(1)<<19) != 0 {
		builder.BoundedUint(message.UsedStorageBytes, 18446744073709551615)
	}
	if message.Presence&(uint64(1)<<20) != 0 {
		builder.BoundedUint(message.StorageUsagePPM, 1000000)
	}
	if message.Presence&(uint64(1)<<21) != 0 {
		builder.BoundedUint(message.InodeUsagePPM, 1000000)
	}
	if message.Presence&(uint64(1)<<22) != 0 {
		builder.String(message.StorageDevice, 160)
	}
	if message.Presence&(uint64(1)<<23) != 0 {
		builder.String(message.StorageFilesystem, 64)
	}
	if message.Presence&(uint64(1)<<24) != 0 {
		builder.String(message.StorageMountpoint, 4096)
	}
	if message.Presence&(uint64(1)<<25) != 0 {
		builder.String(message.StorageModel, 160)
	}
	if message.Presence&(uint64(1)<<26) != 0 {
		builder.BoundedUint(message.StorageType, 16)
	}
	if message.Presence&(uint64(1)<<27) != 0 {
		builder.Bool(message.StorageReadOnly)
	}
	if message.Presence&(uint64(1)<<28) != 0 {
		appendApplicationUsage(builder, message.ApplicationTypes)
	}
	return builder.Bytes()
}

// UnmarshalBinary replaces the message with one exact canonical Heartbeat body.
func (message *Heartbeat) UnmarshalBinary(body []byte) error {
	parser := NewParser(body)
	var decoded Heartbeat
	decoded.Presence = parser.Presence(29)
	decoded.Hostname = parser.String(120)
	if decoded.Presence&(uint64(1)<<0) != 0 {
		decoded.OSVersion = parser.String(120)
	}
	if decoded.Presence&(uint64(1)<<1) != 0 {
		decoded.CPULoadPPM = parser.Uint(1000000)
	}
	if decoded.Presence&(uint64(1)<<2) != 0 {
		decoded.RAMUsagePPM = parser.Uint(1000000)
	}
	if decoded.Presence&(uint64(1)<<3) != 0 {
		decoded.UptimeSeconds = parser.Uint(3155760000)
	}
	if decoded.Presence&(uint64(1)<<4) != 0 {
		decoded.CPUModel = parser.String(160)
	}
	if decoded.Presence&(uint64(1)<<5) != 0 {
		decoded.CPUCores = parser.Uint(4096)
	}
	if decoded.Presence&(uint64(1)<<6) != 0 {
		decoded.CPUThreads = parser.Uint(8192)
	}
	if decoded.Presence&(uint64(1)<<7) != 0 {
		decoded.TotalRAMBytes = parser.Uint(18446744073709551615)
	}
	if decoded.Presence&(uint64(1)<<8) != 0 {
		decoded.GPUDevices = parser.StringList(32, 160, 4096)
	}
	if decoded.Presence&(uint64(1)<<9) != 0 {
		decoded.NetworkName = parser.String(120)
	}
	if decoded.Presence&(uint64(1)<<10) != 0 {
		decoded.NetworkAddresses = parser.StringList(64, 64, 4096)
	}
	if decoded.Presence&(uint64(1)<<11) != 0 {
		decoded.KernelVersion = parser.String(120)
	}
	if decoded.Presence&(uint64(1)<<12) != 0 {
		decoded.CPUFrequencyMHz = parser.Uint(1000000)
	}
	if decoded.Presence&(uint64(1)<<13) != 0 {
		decoded.NetworkOnline = parser.Bool()
	}
	if decoded.Presence&(uint64(1)<<14) != 0 {
		decoded.LinkSpeedMbps = parser.Uint(1000000000)
	}
	if decoded.Presence&(uint64(1)<<15) != 0 {
		decoded.NetworkType = parser.Uint(16)
	}
	if decoded.Presence&(uint64(1)<<16) != 0 {
		decoded.TotalStorageBytes = parser.Uint(18446744073709551615)
	}
	if decoded.Presence&(uint64(1)<<17) != 0 {
		decoded.AvailableStorageBytes = parser.Uint(18446744073709551615)
	}
	if decoded.Presence&(uint64(1)<<18) != 0 {
		decoded.NetworkSSID = parser.String(128)
	}
	if decoded.Presence&(uint64(1)<<19) != 0 {
		decoded.UsedStorageBytes = parser.Uint(18446744073709551615)
	}
	if decoded.Presence&(uint64(1)<<20) != 0 {
		decoded.StorageUsagePPM = parser.Uint(1000000)
	}
	if decoded.Presence&(uint64(1)<<21) != 0 {
		decoded.InodeUsagePPM = parser.Uint(1000000)
	}
	if decoded.Presence&(uint64(1)<<22) != 0 {
		decoded.StorageDevice = parser.String(160)
	}
	if decoded.Presence&(uint64(1)<<23) != 0 {
		decoded.StorageFilesystem = parser.String(64)
	}
	if decoded.Presence&(uint64(1)<<24) != 0 {
		decoded.StorageMountpoint = parser.String(4096)
	}
	if decoded.Presence&(uint64(1)<<25) != 0 {
		decoded.StorageModel = parser.String(160)
	}
	if decoded.Presence&(uint64(1)<<26) != 0 {
		decoded.StorageType = parser.Uint(16)
	}
	if decoded.Presence&(uint64(1)<<27) != 0 {
		decoded.StorageReadOnly = parser.Bool()
	}
	if decoded.Presence&(uint64(1)<<28) != 0 {
		decoded.ApplicationTypes = parseApplicationUsage(parser)
	}
	if err := parser.Done(); err != nil {
		return err
	}
	*message = decoded
	return nil
}

// Attestation is the canonical revision 1 body for MessageAttestation.
type Attestation struct {
	Hostname              string
	OSVersion             string
	RequiresAttestation   bool
	Browsers              []BrowserObservation
	InstalledApplications []string
}

// MarshalBinary returns the canonical bounded Attestation body.
func (message Attestation) MarshalBinary() ([]byte, error) {
	builder := NewBuilder(256)
	builder.String(message.Hostname, 120)
	builder.String(message.OSVersion, 120)
	builder.Bool(message.RequiresAttestation)
	appendBrowserObservations(builder, message.Browsers)
	builder.StringList(message.InstalledApplications, 200, 120, 32768)
	return builder.Bytes()
}

// UnmarshalBinary replaces the message with one exact canonical Attestation body.
func (message *Attestation) UnmarshalBinary(body []byte) error {
	parser := NewParser(body)
	var decoded Attestation
	decoded.Hostname = parser.String(120)
	decoded.OSVersion = parser.String(120)
	decoded.RequiresAttestation = parser.Bool()
	decoded.Browsers = parseBrowserObservations(parser)
	decoded.InstalledApplications = parser.StringList(200, 120, 32768)
	if err := parser.Done(); err != nil {
		return err
	}
	*message = decoded
	return nil
}

// LogEntry is the canonical revision 1 body for MessageLogEntry.
type LogEntry struct {
	Level     uint64
	Component uint64
	EventCode uint64
	Detail    string
}

// MarshalBinary returns the canonical bounded LogEntry body.
func (message LogEntry) MarshalBinary() ([]byte, error) {
	builder := NewBuilder(256)
	builder.BoundedUint(message.Level, 4)
	builder.BoundedUint(message.Component, 255)
	builder.BoundedUint(message.EventCode, 65535)
	builder.String(message.Detail, 512)
	return builder.Bytes()
}

// UnmarshalBinary replaces the message with one exact canonical LogEntry body.
func (message *LogEntry) UnmarshalBinary(body []byte) error {
	parser := NewParser(body)
	var decoded LogEntry
	decoded.Level = parser.Uint(4)
	decoded.Component = parser.Uint(255)
	decoded.EventCode = parser.Uint(65535)
	decoded.Detail = parser.String(512)
	if err := parser.Done(); err != nil {
		return err
	}
	*message = decoded
	return nil
}

// Command is the canonical revision 1 body for MessageCommand.
type Command struct {
	SignedEnvelope []byte
}

// MarshalBinary returns the canonical bounded Command body.
func (message Command) MarshalBinary() ([]byte, error) {
	builder := NewBuilder(256)
	builder.BytesField(message.SignedEnvelope, 131072)
	return builder.Bytes()
}

// UnmarshalBinary replaces the message with one exact canonical Command body.
func (message *Command) UnmarshalBinary(body []byte) error {
	parser := NewParser(body)
	var decoded Command
	decoded.SignedEnvelope = parser.BytesField(131072)
	if err := parser.Done(); err != nil {
		return err
	}
	*message = decoded
	return nil
}

// CommandResult is the canonical revision 1 body for MessageCommandResult.
type CommandResult struct {
	// Presence selects assigned optional fields; unassigned bits are rejected.
	Presence                 uint64
	CommandType              string
	State                    uint64
	ReasonCode               uint64
	ReasonText               string
	RespondedAtMilliseconds  uint64
	Hostname                 string
	TerminalSessionID        string
	TerminalShell            string
	TerminalWorkingDirectory string
	TerminalExitCode         int64
	ResultRevision           uint64
	Result                   []byte
}

// MarshalBinary returns the canonical bounded CommandResult body.
func (message CommandResult) MarshalBinary() ([]byte, error) {
	builder := NewBuilder(256)
	builder.Presence(message.Presence, 6)
	builder.String(message.CommandType, 64)
	builder.BoundedUint(message.State, 8)
	builder.BoundedUint(message.ReasonCode, 65535)
	if message.Presence&(uint64(1)<<0) != 0 {
		builder.String(message.ReasonText, 512)
	}
	builder.BoundedUint(message.RespondedAtMilliseconds, 4102444800000)
	builder.String(message.Hostname, 120)
	if message.Presence&(uint64(1)<<1) != 0 {
		builder.String(message.TerminalSessionID, 128)
	}
	if message.Presence&(uint64(1)<<2) != 0 {
		builder.String(message.TerminalShell, 32)
	}
	if message.Presence&(uint64(1)<<3) != 0 {
		builder.String(message.TerminalWorkingDirectory, 4096)
	}
	if message.Presence&(uint64(1)<<4) != 0 {
		builder.BoundedSInt(message.TerminalExitCode, 2147483647)
	}
	builder.BoundedUint(message.ResultRevision, 255)
	if message.Presence&(uint64(1)<<5) != 0 {
		builder.BytesField(message.Result, 10485760)
	}
	return builder.Bytes()
}

// UnmarshalBinary replaces the message with one exact canonical CommandResult body.
func (message *CommandResult) UnmarshalBinary(body []byte) error {
	parser := NewParser(body)
	var decoded CommandResult
	decoded.Presence = parser.Presence(6)
	decoded.CommandType = parser.String(64)
	decoded.State = parser.Uint(8)
	decoded.ReasonCode = parser.Uint(65535)
	if decoded.Presence&(uint64(1)<<0) != 0 {
		decoded.ReasonText = parser.String(512)
	}
	decoded.RespondedAtMilliseconds = parser.Uint(4102444800000)
	decoded.Hostname = parser.String(120)
	if decoded.Presence&(uint64(1)<<1) != 0 {
		decoded.TerminalSessionID = parser.String(128)
	}
	if decoded.Presence&(uint64(1)<<2) != 0 {
		decoded.TerminalShell = parser.String(32)
	}
	if decoded.Presence&(uint64(1)<<3) != 0 {
		decoded.TerminalWorkingDirectory = parser.String(4096)
	}
	if decoded.Presence&(uint64(1)<<4) != 0 {
		decoded.TerminalExitCode = parser.SInt(2147483647)
	}
	decoded.ResultRevision = parser.Uint(255)
	if decoded.Presence&(uint64(1)<<5) != 0 {
		decoded.Result = parser.BytesField(10485760)
	}
	if err := parser.Done(); err != nil {
		return err
	}
	*message = decoded
	return nil
}

// CommandCancel is the canonical revision 1 body for MessageCommandCancel.
type CommandCancel struct {
	Reason uint64
}

// MarshalBinary returns the canonical bounded CommandCancel body.
func (message CommandCancel) MarshalBinary() ([]byte, error) {
	builder := NewBuilder(256)
	builder.BoundedUint(message.Reason, 32)
	return builder.Bytes()
}

// UnmarshalBinary replaces the message with one exact canonical CommandCancel body.
func (message *CommandCancel) UnmarshalBinary(body []byte) error {
	parser := NewParser(body)
	var decoded CommandCancel
	decoded.Reason = parser.Uint(32)
	if err := parser.Done(); err != nil {
		return err
	}
	*message = decoded
	return nil
}

// CommandState is the canonical revision 1 body for MessageCommandState.
type CommandState struct {
	State uint64
}

// MarshalBinary returns the canonical bounded CommandState body.
func (message CommandState) MarshalBinary() ([]byte, error) {
	builder := NewBuilder(256)
	builder.BoundedUint(message.State, 16)
	return builder.Bytes()
}

// UnmarshalBinary replaces the message with one exact canonical CommandState body.
func (message *CommandState) UnmarshalBinary(body []byte) error {
	parser := NewParser(body)
	var decoded CommandState
	decoded.State = parser.Uint(16)
	if err := parser.Done(); err != nil {
		return err
	}
	*message = decoded
	return nil
}

// TransferOpen is the canonical revision 1 body for MessageTransferOpen.
type TransferOpen struct {
	TransferID            [16]byte
	SignedCapability      []byte
	Direction             uint64
	ManifestDigest        [32]byte
	ExpectedTotalSize     uint64
	ChunkSize             uint64
	ExpiresAtMilliseconds uint64
}

// MarshalBinary returns the canonical bounded TransferOpen body.
func (message TransferOpen) MarshalBinary() ([]byte, error) {
	builder := NewBuilder(256)
	builder.Fixed16(message.TransferID)
	builder.BytesField(message.SignedCapability, 8192)
	builder.BoundedUint(message.Direction, 2)
	builder.Opaque32(message.ManifestDigest)
	builder.BoundedUint(message.ExpectedTotalSize, 1099511627776)
	builder.BoundedUint(message.ChunkSize, 4194304)
	builder.BoundedUint(message.ExpiresAtMilliseconds, 4102444800000)
	return builder.Bytes()
}

// UnmarshalBinary replaces the message with one exact canonical TransferOpen body.
func (message *TransferOpen) UnmarshalBinary(body []byte) error {
	parser := NewParser(body)
	var decoded TransferOpen
	decoded.TransferID = parser.Fixed16()
	decoded.SignedCapability = parser.BytesField(8192)
	decoded.Direction = parser.Uint(2)
	decoded.ManifestDigest = parser.Opaque32()
	decoded.ExpectedTotalSize = parser.Uint(1099511627776)
	decoded.ChunkSize = parser.Uint(4194304)
	decoded.ExpiresAtMilliseconds = parser.Uint(4102444800000)
	if err := parser.Done(); err != nil {
		return err
	}
	*message = decoded
	return nil
}

// TransferChunk is the canonical revision 1 body for MessageTransferChunk.
type TransferChunk struct {
	ChunkIndex      uint64
	ChunkLength     uint64
	DigestAlgorithm uint64
	Digest          [32]byte
	Data            []byte
}

// MarshalBinary returns the canonical bounded TransferChunk body.
func (message TransferChunk) MarshalBinary() ([]byte, error) {
	builder := NewBuilder(256)
	builder.BoundedUint(message.ChunkIndex, 1048576)
	builder.BoundedUint(message.ChunkLength, 4194304)
	builder.BoundedUint(message.DigestAlgorithm, 1)
	builder.Opaque32(message.Digest)
	builder.BytesField(message.Data, 4194304)
	return builder.Bytes()
}

// UnmarshalBinary replaces the message with one exact canonical TransferChunk body.
func (message *TransferChunk) UnmarshalBinary(body []byte) error {
	parser := NewParser(body)
	var decoded TransferChunk
	decoded.ChunkIndex = parser.Uint(1048576)
	decoded.ChunkLength = parser.Uint(4194304)
	decoded.DigestAlgorithm = parser.Uint(1)
	decoded.Digest = parser.Opaque32()
	decoded.Data = parser.BytesField(4194304)
	if err := parser.Done(); err != nil {
		return err
	}
	*message = decoded
	return nil
}

// TransferChunkAck is the canonical revision 1 body for MessageTransferChunkAck.
type TransferChunkAck struct {
	ChunkIndex uint64
	Digest     [32]byte
}

// MarshalBinary returns the canonical bounded TransferChunkAck body.
func (message TransferChunkAck) MarshalBinary() ([]byte, error) {
	builder := NewBuilder(256)
	builder.BoundedUint(message.ChunkIndex, 1048576)
	builder.Opaque32(message.Digest)
	return builder.Bytes()
}

// UnmarshalBinary replaces the message with one exact canonical TransferChunkAck body.
func (message *TransferChunkAck) UnmarshalBinary(body []byte) error {
	parser := NewParser(body)
	var decoded TransferChunkAck
	decoded.ChunkIndex = parser.Uint(1048576)
	decoded.Digest = parser.Opaque32()
	if err := parser.Done(); err != nil {
		return err
	}
	*message = decoded
	return nil
}

// TransferFinalize is the canonical revision 1 body for MessageTransferFinalize.
type TransferFinalize struct {
	ExpectedChunkCount uint64
	TotalSize          uint64
	WholeObjectDigest  [32]byte
}

// MarshalBinary returns the canonical bounded TransferFinalize body.
func (message TransferFinalize) MarshalBinary() ([]byte, error) {
	builder := NewBuilder(256)
	builder.BoundedUint(message.ExpectedChunkCount, 1048576)
	builder.BoundedUint(message.TotalSize, 1099511627776)
	builder.Opaque32(message.WholeObjectDigest)
	return builder.Bytes()
}

// UnmarshalBinary replaces the message with one exact canonical TransferFinalize body.
func (message *TransferFinalize) UnmarshalBinary(body []byte) error {
	parser := NewParser(body)
	var decoded TransferFinalize
	decoded.ExpectedChunkCount = parser.Uint(1048576)
	decoded.TotalSize = parser.Uint(1099511627776)
	decoded.WholeObjectDigest = parser.Opaque32()
	if err := parser.Done(); err != nil {
		return err
	}
	*message = decoded
	return nil
}

// TransferAbort is the canonical revision 1 body for MessageTransferAbort.
type TransferAbort struct {
	Reason uint64
}

// MarshalBinary returns the canonical bounded TransferAbort body.
func (message TransferAbort) MarshalBinary() ([]byte, error) {
	builder := NewBuilder(256)
	builder.BoundedUint(message.Reason, 32)
	return builder.Bytes()
}

// UnmarshalBinary replaces the message with one exact canonical TransferAbort body.
func (message *TransferAbort) UnmarshalBinary(body []byte) error {
	parser := NewParser(body)
	var decoded TransferAbort
	decoded.Reason = parser.Uint(32)
	if err := parser.Done(); err != nil {
		return err
	}
	*message = decoded
	return nil
}

// MediaOpen is the canonical revision 1 body for MessageMediaOpen.
type MediaOpen struct {
	GenerationID      [16]byte
	Codec             uint64
	Width             uint64
	Height            uint64
	FrameRateCap      uint64
	MaximumFrameBytes uint64
}

// MarshalBinary returns the canonical bounded MediaOpen body.
func (message MediaOpen) MarshalBinary() ([]byte, error) {
	builder := NewBuilder(256)
	builder.Fixed16(message.GenerationID)
	builder.BoundedUint(message.Codec, 8)
	builder.BoundedUint(message.Width, 16384)
	builder.BoundedUint(message.Height, 16384)
	builder.BoundedUint(message.FrameRateCap, 120)
	builder.BoundedUint(message.MaximumFrameBytes, 10485760)
	return builder.Bytes()
}

// UnmarshalBinary replaces the message with one exact canonical MediaOpen body.
func (message *MediaOpen) UnmarshalBinary(body []byte) error {
	parser := NewParser(body)
	var decoded MediaOpen
	decoded.GenerationID = parser.Fixed16()
	decoded.Codec = parser.Uint(8)
	decoded.Width = parser.Uint(16384)
	decoded.Height = parser.Uint(16384)
	decoded.FrameRateCap = parser.Uint(120)
	decoded.MaximumFrameBytes = parser.Uint(10485760)
	if err := parser.Done(); err != nil {
		return err
	}
	*message = decoded
	return nil
}

// MediaFrame is the canonical revision 1 body for MessageMediaFrame.
type MediaFrame struct {
	GenerationID           [16]byte
	FrameNumber            uint64
	CapturedAtMilliseconds uint64
	Keyframe               bool
	ContentType            uint64
	Data                   []byte
}

// MarshalBinary returns the canonical bounded MediaFrame body.
func (message MediaFrame) MarshalBinary() ([]byte, error) {
	builder := NewBuilder(256)
	builder.Fixed16(message.GenerationID)
	builder.BoundedUint(message.FrameNumber, 18446744073709551615)
	builder.BoundedUint(message.CapturedAtMilliseconds, 4102444800000)
	builder.Bool(message.Keyframe)
	builder.BoundedUint(message.ContentType, 8)
	builder.BytesField(message.Data, 10485760)
	return builder.Bytes()
}

// UnmarshalBinary replaces the message with one exact canonical MediaFrame body.
func (message *MediaFrame) UnmarshalBinary(body []byte) error {
	parser := NewParser(body)
	var decoded MediaFrame
	decoded.GenerationID = parser.Fixed16()
	decoded.FrameNumber = parser.Uint(18446744073709551615)
	decoded.CapturedAtMilliseconds = parser.Uint(4102444800000)
	decoded.Keyframe = parser.Bool()
	decoded.ContentType = parser.Uint(8)
	decoded.Data = parser.BytesField(10485760)
	if err := parser.Done(); err != nil {
		return err
	}
	*message = decoded
	return nil
}

// MediaClose is the canonical revision 1 body for MessageMediaClose.
type MediaClose struct {
	Reason          uint64
	LastFrameNumber uint64
}

// MarshalBinary returns the canonical bounded MediaClose body.
func (message MediaClose) MarshalBinary() ([]byte, error) {
	builder := NewBuilder(256)
	builder.BoundedUint(message.Reason, 32)
	builder.BoundedUint(message.LastFrameNumber, 18446744073709551615)
	return builder.Bytes()
}

// UnmarshalBinary replaces the message with one exact canonical MediaClose body.
func (message *MediaClose) UnmarshalBinary(body []byte) error {
	parser := NewParser(body)
	var decoded MediaClose
	decoded.Reason = parser.Uint(32)
	decoded.LastFrameNumber = parser.Uint(18446744073709551615)
	if err := parser.Done(); err != nil {
		return err
	}
	*message = decoded
	return nil
}
