// Code generated by go run ./cmd/wiregen; DO NOT EDIT.

package wire

// StreamInitiator identifies which authenticated peer may open a stream.
type StreamInitiator uint8

const (
	// InitiatorAgent permits only the authenticated agent.
	InitiatorAgent StreamInitiator = iota + 1
	// InitiatorGateway permits only the gateway.
	InitiatorGateway
	// InitiatorEither permits either authenticated peer.
	InitiatorEither
)

// StreamDirection identifies the QUIC stream direction required by XBP.
type StreamDirection uint8

const (
	// DirectionUnidirectional carries bytes from its initiator only.
	DirectionUnidirectional StreamDirection = iota + 1
	// DirectionBidirectional carries bytes in both directions.
	DirectionBidirectional
)

// StreamSpecification is the immutable topology and frame bound for a stream kind.
type StreamSpecification struct {
	Name              string
	MaximumFrameBytes uint32
	Initiator         StreamInitiator
	Direction         StreamDirection
	Mandatory         bool
}

// SpecificationForStream returns the reviewed XBP stream contract.
func SpecificationForStream(kind StreamKind) (StreamSpecification, bool) {
	switch kind {
	case StreamControl:
		return StreamSpecification{Name: "control", MaximumFrameBytes: 65536, Initiator: InitiatorAgent, Direction: DirectionBidirectional, Mandatory: true}, true
	case StreamEvents:
		return StreamSpecification{Name: "events", MaximumFrameBytes: 262144, Initiator: InitiatorAgent, Direction: DirectionUnidirectional, Mandatory: true}, true
	case StreamCommands:
		return StreamSpecification{Name: "commands", MaximumFrameBytes: 262144, Initiator: InitiatorGateway, Direction: DirectionUnidirectional, Mandatory: true}, true
	case StreamTransfer:
		return StreamSpecification{Name: "transfer", MaximumFrameBytes: 4259840, Initiator: InitiatorEither, Direction: DirectionBidirectional, Mandatory: false}, true
	case StreamTerminal:
		return StreamSpecification{Name: "terminal", MaximumFrameBytes: 262144, Initiator: InitiatorGateway, Direction: DirectionBidirectional, Mandatory: false}, true
	case StreamMedia:
		return StreamSpecification{Name: "media", MaximumFrameBytes: 10485760, Initiator: InitiatorAgent, Direction: DirectionUnidirectional, Mandatory: false}, true
	case StreamDiagnostics:
		return StreamSpecification{Name: "diagnostics", MaximumFrameBytes: 65536, Initiator: InitiatorEither, Direction: DirectionBidirectional, Mandatory: false}, true
	default:
		return StreamSpecification{}, false
	}
}

const (
	// MessageClientHello identifies ClientHello revision 1.
	MessageClientHello MessageType = 0x1
	// MessageServerHello identifies ServerHello revision 1.
	MessageServerHello MessageType = 0x2
	// MessagePing identifies Ping revision 1.
	MessagePing MessageType = 0x3
	// MessagePong identifies Pong revision 1.
	MessagePong MessageType = 0x4
	// MessageMessageAck identifies MessageAck revision 1.
	MessageMessageAck MessageType = 0x5
	// MessageProtocolError identifies ProtocolError revision 1.
	MessageProtocolError MessageType = 0x6
	// MessageDrain identifies Drain revision 1.
	MessageDrain MessageType = 0x7
	// MessageSessionReplaced identifies SessionReplaced revision 1.
	MessageSessionReplaced MessageType = 0x8
	// MessageHeartbeat identifies Heartbeat revision 1.
	MessageHeartbeat MessageType = 0x100
	// MessageAttestation identifies Attestation revision 1.
	MessageAttestation MessageType = 0x101
	// MessageLogEntry identifies LogEntry revision 1.
	MessageLogEntry MessageType = 0x102
	// MessageCommand identifies Command revision 1.
	MessageCommand MessageType = 0x200
	// MessageCommandResult identifies CommandResult revision 1.
	MessageCommandResult MessageType = 0x201
	// MessageCommandCancel identifies CommandCancel revision 1.
	MessageCommandCancel MessageType = 0x202
	// MessageCommandState identifies CommandState revision 1.
	MessageCommandState MessageType = 0x203
	// MessageTransferOpen identifies TransferOpen revision 1.
	MessageTransferOpen MessageType = 0x300
	// MessageTransferChunk identifies TransferChunk revision 1.
	MessageTransferChunk MessageType = 0x301
	// MessageTransferChunkAck identifies TransferChunkAck revision 1.
	MessageTransferChunkAck MessageType = 0x302
	// MessageTransferFinalize identifies TransferFinalize revision 1.
	MessageTransferFinalize MessageType = 0x303
	// MessageTransferAbort identifies TransferAbort revision 1.
	MessageTransferAbort MessageType = 0x304
	// MessageMediaOpen identifies MediaOpen revision 1.
	MessageMediaOpen MessageType = 0x500
	// MessageMediaFrame identifies MediaFrame revision 1.
	MessageMediaFrame MessageType = 0x501
	// MessageMediaClose identifies MediaClose revision 1.
	MessageMediaClose MessageType = 0x502
)

// MessageDescriptor describes one immutable registry assignment.
type MessageDescriptor struct {
	Type            MessageType
	Name            string
	Stream          StreamKind
	Revision        uint8
	Acknowledgement string
	CommitPoint     string
	RetryContract   string
}

// DescriptorForMessage returns the immutable assignment for a message type.
func DescriptorForMessage(messageType MessageType) (MessageDescriptor, bool) {
	switch messageType {
	case MessageClientHello:
		return MessageDescriptor{Type: MessageClientHello, Name: "ClientHello", Stream: StreamControl, Revision: 1, Acknowledgement: "required", CommitPoint: "validated", RetryContract: "never"}, true
	case MessageServerHello:
		return MessageDescriptor{Type: MessageServerHello, Name: "ServerHello", Stream: StreamControl, Revision: 1, Acknowledgement: "none", CommitPoint: "validated", RetryContract: "never"}, true
	case MessagePing:
		return MessageDescriptor{Type: MessagePing, Name: "Ping", Stream: StreamControl, Revision: 1, Acknowledgement: "none", CommitPoint: "decoded", RetryContract: "never"}, true
	case MessagePong:
		return MessageDescriptor{Type: MessagePong, Name: "Pong", Stream: StreamControl, Revision: 1, Acknowledgement: "none", CommitPoint: "decoded", RetryContract: "never"}, true
	case MessageMessageAck:
		return MessageDescriptor{Type: MessageMessageAck, Name: "MessageAck", Stream: StreamControl, Revision: 1, Acknowledgement: "none", CommitPoint: "decoded", RetryContract: "never"}, true
	case MessageProtocolError:
		return MessageDescriptor{Type: MessageProtocolError, Name: "ProtocolError", Stream: StreamControl, Revision: 1, Acknowledgement: "none", CommitPoint: "decoded", RetryContract: "never"}, true
	case MessageDrain:
		return MessageDescriptor{Type: MessageDrain, Name: "Drain", Stream: StreamControl, Revision: 1, Acknowledgement: "required", CommitPoint: "validated", RetryContract: "never"}, true
	case MessageSessionReplaced:
		return MessageDescriptor{Type: MessageSessionReplaced, Name: "SessionReplaced", Stream: StreamControl, Revision: 1, Acknowledgement: "none", CommitPoint: "validated", RetryContract: "never"}, true
	case MessageHeartbeat:
		return MessageDescriptor{Type: MessageHeartbeat, Name: "Heartbeat", Stream: StreamEvents, Revision: 1, Acknowledgement: "required", CommitPoint: "published", RetryContract: "latest-supersedes-uncommitted"}, true
	case MessageAttestation:
		return MessageDescriptor{Type: MessageAttestation, Name: "Attestation", Stream: StreamEvents, Revision: 1, Acknowledgement: "required", CommitPoint: "published", RetryContract: "same-operation"}, true
	case MessageLogEntry:
		return MessageDescriptor{Type: MessageLogEntry, Name: "LogEntry", Stream: StreamEvents, Revision: 1, Acknowledgement: "required", CommitPoint: "published", RetryContract: "never"}, true
	case MessageCommand:
		return MessageDescriptor{Type: MessageCommand, Name: "Command", Stream: StreamCommands, Revision: 1, Acknowledgement: "required", CommitPoint: "persisted", RetryContract: "reconciliation-only"}, true
	case MessageCommandResult:
		return MessageDescriptor{Type: MessageCommandResult, Name: "CommandResult", Stream: StreamEvents, Revision: 1, Acknowledgement: "required", CommitPoint: "operation-terminal", RetryContract: "same-operation"}, true
	case MessageCommandCancel:
		return MessageDescriptor{Type: MessageCommandCancel, Name: "CommandCancel", Stream: StreamCommands, Revision: 1, Acknowledgement: "required", CommitPoint: "validated", RetryContract: "same-operation"}, true
	case MessageCommandState:
		return MessageDescriptor{Type: MessageCommandState, Name: "CommandState", Stream: StreamEvents, Revision: 1, Acknowledgement: "required", CommitPoint: "persisted", RetryContract: "same-operation"}, true
	case MessageTransferOpen:
		return MessageDescriptor{Type: MessageTransferOpen, Name: "TransferOpen", Stream: StreamTransfer, Revision: 1, Acknowledgement: "required", CommitPoint: "validated", RetryContract: "same-operation"}, true
	case MessageTransferChunk:
		return MessageDescriptor{Type: MessageTransferChunk, Name: "TransferChunk", Stream: StreamTransfer, Revision: 1, Acknowledgement: "required", CommitPoint: "persisted", RetryContract: "same-operation"}, true
	case MessageTransferChunkAck:
		return MessageDescriptor{Type: MessageTransferChunkAck, Name: "TransferChunkAck", Stream: StreamTransfer, Revision: 1, Acknowledgement: "none", CommitPoint: "persisted", RetryContract: "same-operation"}, true
	case MessageTransferFinalize:
		return MessageDescriptor{Type: MessageTransferFinalize, Name: "TransferFinalize", Stream: StreamTransfer, Revision: 1, Acknowledgement: "required", CommitPoint: "persisted", RetryContract: "same-operation"}, true
	case MessageTransferAbort:
		return MessageDescriptor{Type: MessageTransferAbort, Name: "TransferAbort", Stream: StreamTransfer, Revision: 1, Acknowledgement: "required", CommitPoint: "persisted", RetryContract: "same-operation"}, true
	case MessageMediaOpen:
		return MessageDescriptor{Type: MessageMediaOpen, Name: "MediaOpen", Stream: StreamMedia, Revision: 1, Acknowledgement: "required", CommitPoint: "validated", RetryContract: "never"}, true
	case MessageMediaFrame:
		return MessageDescriptor{Type: MessageMediaFrame, Name: "MediaFrame", Stream: StreamMedia, Revision: 1, Acknowledgement: "none", CommitPoint: "decoded", RetryContract: "never"}, true
	case MessageMediaClose:
		return MessageDescriptor{Type: MessageMediaClose, Name: "MediaClose", Stream: StreamMedia, Revision: 1, Acknowledgement: "none", CommitPoint: "decoded", RetryContract: "never"}, true
	default:
		return MessageDescriptor{}, false
	}
}

// ValidateMessageForStream rejects unassigned types, wrong lanes, and revisions.
func ValidateMessageForStream(kind StreamKind, messageType MessageType, revision uint8) error {
	descriptor, ok := DescriptorForMessage(messageType)
	if !ok || descriptor.Stream != kind || descriptor.Revision != revision {
		return ErrUnexpectedMessage
	}
	return nil
}
