// Command wiregen validates the canonical XBP schema and emits deterministic
// Go registries, message codecs, and the versioned byte-layout reference.
package main

import (
	"bytes"
	"crypto/sha256"
	"encoding/binary"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

const (
	generatedHeader               = "// Code generated by go run ./cmd/wiregen; DO NOT EDIT.\n"
	fieldTypeBool                 = "bool"
	fieldTypeBytes                = "bytes"
	fieldTypeString               = "string"
	fieldTypeFixed16              = "fixed16"
	fieldTypeOpaque32             = "opaque32"
	fieldTypeStringList           = "string_list"
	fieldTypeBrowserList          = "browser_list"
	fieldTypeApplicationUsageList = "application_usage_list"
	generatedDirectoryMode        = 0o755
	generatedFileMode             = 0o644
	structuralGoldenArtifacts     = 2
	fixed16Bytes                  = 16
	opaque32Bytes                 = 32
	referenceFrameHeaderCapacity  = 8
	baseGeneratedFileCount        = 5
)

type protocolSchema struct {
	Protocol protocolDefinition  `json:"protocol"`
	Streams  []streamDefinition  `json:"streams"`
	Messages []messageDefinition `json:"messages"`
}

type protocolDefinition struct {
	Name  string `json:"name"`
	Major uint8  `json:"major"`
	Minor uint16 `json:"minor"`
	ALPN  string `json:"alpn"`
}

type streamDefinition struct {
	Name              string `json:"name"`
	GoName            string `json:"go_name"`
	Code              uint8  `json:"code"`
	MaximumFrameBytes uint32 `json:"maximum_frame_bytes"`
	Initiator         string `json:"initiator"`
	Direction         string `json:"direction"`
	Mandatory         bool   `json:"mandatory"`
}

type messageDefinition struct {
	Name            string            `json:"name"`
	GoName          string            `json:"go_name"`
	ID              uint16            `json:"id"`
	Stream          string            `json:"stream"`
	Revision        uint8             `json:"revision"`
	Acknowledgement string            `json:"acknowledgement"`
	Commit          string            `json:"commit"`
	Retry           string            `json:"retry"`
	PresenceBits    uint8             `json:"presence_bits"`
	Fields          []fieldDefinition `json:"fields"`
}

type fieldDefinition struct {
	Name             string `json:"name"`
	GoName           string `json:"go_name"`
	Type             string `json:"type"`
	Maximum          uint64 `json:"maximum"`
	CountMaximum     int    `json:"count_maximum"`
	ItemMaximum      int    `json:"item_maximum"`
	AggregateMaximum int    `json:"aggregate_maximum"`
	OptionalBit      *uint8 `json:"optional_bit"`
	Trust            string `json:"trust"`
}

type registryHistory struct {
	Major         uint8             `json:"major"`
	Assigned      map[string]string `json:"assigned"`
	Compatibility map[string]string `json:"compatibility"`
	Tombstoned    map[string]string `json:"tombstoned"`
}

type generatedFile struct {
	path string
	data []byte
}

func main() {
	check := flag.Bool("check", false, "verify generated files without changing them")
	printCompatibility := flag.Bool("print-compatibility", false, "print compatibility signatures for schema review")
	root := flag.String("root", ".", "platform/shared module root")
	flag.Parse()

	if *printCompatibility {
		if err := printCompatibilitySignatures(*root); err != nil {
			fmt.Fprintln(os.Stderr, err)
			os.Exit(1)
		}
		return
	}
	if err := run(*root, *check); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func printCompatibilitySignatures(root string) error {
	schema, err := readJSONFile[protocolSchema](filepath.Join(root, "protocol", "xbp-v1.yaml"))
	if err != nil {
		return err
	}
	for _, message := range schema.Messages {
		signature := messageCompatibilitySignature(message)
		if signature == "" {
			return fmt.Errorf("encode compatibility signature for %s", message.Name)
		}
		fmt.Printf("%d %s\n", message.ID, signature)
	}
	return nil
}

func run(root string, check bool) error {
	schema, err := readJSONFile[protocolSchema](filepath.Join(root, "protocol", "xbp-v1.yaml"))
	if err != nil {
		return err
	}
	history, err := readJSONFile[registryHistory](filepath.Join(root, "protocol", "registry-history.yaml"))
	if err != nil {
		return err
	}
	if err := validateSchema(schema, history); err != nil {
		return fmt.Errorf("validate XBP schema: %w", err)
	}

	files, err := buildGeneratedFiles(root, schema)
	if err != nil {
		return err
	}
	for _, file := range files {
		if check {
			if err := compareGenerated(file); err != nil {
				return err
			}
			continue
		}
		if err := writeGeneratedFile(file); err != nil {
			return err
		}
	}
	return nil
}

func buildGeneratedFiles(root string, schema protocolSchema) ([]generatedFile, error) {
	registry, err := generateRegistry(schema)
	if err != nil {
		return nil, err
	}
	messages, err := generateMessages(schema)
	if err != nil {
		return nil, err
	}
	goldenVectors, err := generateStructuralGoldenVectors(root, schema)
	if err != nil {
		return nil, err
	}
	files := make([]generatedFile, 0, baseGeneratedFileCount+len(goldenVectors))
	files = append(files,
		generatedFile{path: filepath.Join(root, "wire", "registry_generated.go"), data: registry},
		generatedFile{path: filepath.Join(root, "wire", "messages_generated.go"), data: messages},
		generatedFile{path: filepath.Join(root, "protocol", "xbp-v1-wire-reference.md"), data: generateReference(schema)},
		generatedFile{path: filepath.Join(root, "wire", "testdata", "golden", "v1", "log_entry_minimal.bin"), data: []byte{0x09, 0x82, 0x02, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x00}},
		generatedFile{path: filepath.Join(root, "wire", "testdata", "golden", "v1", "log_entry_minimal.json"), data: []byte("{\n  \"stream\": \"events\",\n  \"message_type\": 258,\n  \"schema_revision\": 1,\n  \"flags\": 1,\n  \"sequence\": 1,\n  \"level\": 1,\n  \"component\": 1,\n  \"event_code\": 1,\n  \"detail\": \"\"\n}\n")},
	)
	return append(files, goldenVectors...), nil
}

type structuralGoldenMetadata struct {
	Message        string                  `json:"message"`
	Stream         string                  `json:"stream"`
	MessageType    uint16                  `json:"message_type"`
	SchemaRevision uint8                   `json:"schema_revision"`
	Flags          uint8                   `json:"flags"`
	Sequence       uint64                  `json:"sequence"`
	Fields         []structuralGoldenField `json:"fields"`
}

type structuralGoldenField struct {
	Name     string `json:"name"`
	Encoding string `json:"encoding"`
	Value    any    `json:"value"`
}

func generateStructuralGoldenVectors(root string, schema protocolSchema) ([]generatedFile, error) {
	directory := filepath.Join(root, "wire", "testdata", "golden", "v1")
	files := make([]generatedFile, 0, len(schema.Messages)*structuralGoldenArtifacts)
	for _, message := range schema.Messages {
		body, fields := encodeStructuralMinimum(message)
		flags := uint8(0)
		if message.Acknowledgement == "required" {
			flags = 1
		}
		frame := encodeReferenceFrame(message.ID, message.Revision, flags, body)
		metadata, err := json.MarshalIndent(structuralGoldenMetadata{
			Message: message.Name, Stream: message.Stream, MessageType: message.ID,
			SchemaRevision: message.Revision, Flags: flags, Sequence: 1, Fields: fields,
		}, "", "  ")
		if err != nil {
			return nil, fmt.Errorf("encode %s golden metadata: %w", message.Name, err)
		}
		name := snakeCaseIdentifier(message.Name) + "_structural_minimum"
		files = append(files,
			generatedFile{path: filepath.Join(directory, name+".bin"), data: frame},
			generatedFile{path: filepath.Join(directory, name+".json"), data: append(metadata, '\n')},
		)
	}
	return files, nil
}

func encodeStructuralMinimum(message messageDefinition) ([]byte, []structuralGoldenField) {
	body := make([]byte, 0, len(message.Fields)+1)
	fields := make([]structuralGoldenField, 0, len(message.Fields)+1)
	if message.PresenceBits > 0 {
		body = append(body, 0)
		fields = append(fields, structuralGoldenField{Name: "presence", Encoding: "presence", Value: uint64(0)})
	}
	for _, field := range message.Fields {
		if field.OptionalBit != nil {
			continue
		}
		encoded, value := encodeStructuralMinimumField(field.Type)
		body = append(body, encoded...)
		fields = append(fields, structuralGoldenField{Name: field.Name, Encoding: field.Type, Value: value})
	}
	return body, fields
}

func encodeStructuralMinimumField(fieldType string) ([]byte, any) {
	switch fieldType {
	case fieldTypeBool:
		return []byte{0}, false
	case fieldTypeFixed16:
		return make([]byte, fixed16Bytes), strings.Repeat("00", fixed16Bytes)
	case fieldTypeOpaque32:
		return make([]byte, opaque32Bytes), strings.Repeat("00", opaque32Bytes)
	case fieldTypeString, fieldTypeBytes:
		return []byte{0}, ""
	case fieldTypeStringList, fieldTypeBrowserList, fieldTypeApplicationUsageList:
		return []byte{0}, []any{}
	default:
		return []byte{0}, uint64(0)
	}
}

func encodeReferenceFrame(messageType uint16, revision, flags uint8, body []byte) []byte {
	payload := make([]byte, 0, len(body)+referenceFrameHeaderCapacity)
	payload = binary.AppendUvarint(payload, uint64(messageType))
	payload = append(payload, revision, flags)
	payload = binary.AppendUvarint(payload, 1)
	payload = append(payload, body...)
	frame := binary.AppendUvarint(nil, uint64(len(payload)))
	return append(frame, payload...)
}

func snakeCaseIdentifier(value string) string {
	var result strings.Builder
	for index, character := range value {
		if character >= 'A' && character <= 'Z' {
			if index > 0 {
				result.WriteByte('_')
			}
			character += 'a' - 'A'
		}
		result.WriteRune(character)
	}
	return result.String()
}

func writeGeneratedFile(file generatedFile) error {
	if err := os.MkdirAll(filepath.Dir(file.path), generatedDirectoryMode); err != nil { // #nosec G301 -- generated repository source directories must be traversable by contributors.
		return fmt.Errorf("create generated directory for %s: %w", file.path, err)
	}
	if err := os.WriteFile(file.path, file.data, generatedFileMode); err != nil { // #nosec G306 -- generated repository artifacts use normal source-file permissions.
		return fmt.Errorf("write %s: %w", file.path, err)
	}
	return nil
}

func readJSONFile[T any](path string) (T, error) {
	var result T
	data, err := os.ReadFile(filepath.Clean(path))
	if err != nil {
		return result, fmt.Errorf("read %s: %w", path, err)
	}
	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(&result); err != nil {
		return result, fmt.Errorf("decode %s: %w", path, err)
	}
	if decoder.More() {
		return result, fmt.Errorf("decode %s: trailing document", path)
	}
	return result, nil
}

func validateSchema(schema protocolSchema, history registryHistory) error {
	if err := validateProtocolIdentity(schema.Protocol, history); err != nil {
		return err
	}
	streams, err := validateStreams(schema.Streams)
	if err != nil {
		return err
	}
	messageIDs, err := validateMessages(schema.Messages, streams, history)
	if err != nil {
		return err
	}
	if len(history.Assigned) != len(messageIDs) {
		return errors.New("registry history contains an assigned ID absent from the schema")
	}
	return nil
}

func validateProtocolIdentity(protocol protocolDefinition, history registryHistory) error {
	if protocol.Major != 1 || protocol.Minor != 0 || protocol.ALPN != "xenomorph-agent/1" {
		return errors.New("protocol identity differs from the approved XBP/1 profile")
	}
	if history.Major != protocol.Major {
		return errors.New("registry history major version mismatch")
	}
	return nil
}

func validateStreams(definitions []streamDefinition) (map[string]streamDefinition, error) {
	streams := make(map[string]streamDefinition, len(definitions))
	streamCodes := make(map[uint8]struct{}, len(definitions))
	for _, stream := range definitions {
		if stream.Name == "" || stream.GoName == "" || stream.MaximumFrameBytes == 0 {
			return nil, fmt.Errorf("stream %q has incomplete identity or bounds", stream.Name)
		}
		if _, exists := streams[stream.Name]; exists {
			return nil, fmt.Errorf("duplicate stream name %q", stream.Name)
		}
		if _, exists := streamCodes[stream.Code]; exists {
			return nil, fmt.Errorf("duplicate stream code %d", stream.Code)
		}
		if !oneOf(stream.Initiator, "agent", "gateway", "either") || !oneOf(stream.Direction, "unidirectional", "bidirectional") {
			return nil, fmt.Errorf("stream %q has invalid topology", stream.Name)
		}
		streams[stream.Name] = stream
		streamCodes[stream.Code] = struct{}{}
	}
	return streams, nil
}

func validateMessages(definitions []messageDefinition, streams map[string]streamDefinition, history registryHistory) (map[uint16]string, error) {
	messageIDs := make(map[uint16]string, len(definitions))
	for _, message := range definitions {
		if err := validateMessage(message, streams); err != nil {
			return nil, err
		}
		if previous, exists := messageIDs[message.ID]; exists {
			return nil, fmt.Errorf("message ID %#04x reused by %s and %s", message.ID, previous, message.Name)
		}
		messageIDs[message.ID] = message.Name
		key := strconv.FormatUint(uint64(message.ID), 10)
		if historical, exists := history.Assigned[key]; !exists || historical != message.Name {
			return nil, fmt.Errorf("message %s ID %#04x does not match registry history", message.Name, message.ID)
		}
		if _, tombstoned := history.Tombstoned[key]; tombstoned {
			return nil, fmt.Errorf("message %s reuses tombstoned ID %#04x", message.Name, message.ID)
		}
		signature := messageCompatibilitySignature(message)
		if signature == "" {
			return nil, fmt.Errorf("encode message %s compatibility signature", message.Name)
		}
		if historical := history.Compatibility[key]; historical != signature {
			return nil, fmt.Errorf("message %s revision or field layout differs from compatibility history", message.Name)
		}
	}
	if len(history.Compatibility) != len(messageIDs) {
		return nil, errors.New("compatibility history contains an assignment absent from the schema")
	}
	return messageIDs, nil
}

func messageCompatibilitySignature(message messageDefinition) string {
	type compatibilityField struct {
		Name             string `json:"name"`
		Type             string `json:"type"`
		Maximum          uint64 `json:"maximum"`
		CountMaximum     int    `json:"count_maximum"`
		ItemMaximum      int    `json:"item_maximum"`
		AggregateMaximum int    `json:"aggregate_maximum"`
		OptionalBit      *uint8 `json:"optional_bit"`
	}
	contract := struct {
		Revision     uint8                `json:"revision"`
		PresenceBits uint8                `json:"presence_bits"`
		Fields       []compatibilityField `json:"fields"`
	}{Revision: message.Revision, PresenceBits: message.PresenceBits, Fields: make([]compatibilityField, 0, len(message.Fields))}
	for _, field := range message.Fields {
		contract.Fields = append(contract.Fields, compatibilityField{
			Name: field.Name, Type: field.Type, Maximum: field.Maximum,
			CountMaximum: field.CountMaximum, ItemMaximum: field.ItemMaximum,
			AggregateMaximum: field.AggregateMaximum, OptionalBit: field.OptionalBit,
		})
	}
	encoded, err := json.Marshal(contract)
	if err != nil {
		return ""
	}
	return fmt.Sprintf("sha256:%x", sha256.Sum256(encoded))
}

func validateMessage(message messageDefinition, streams map[string]streamDefinition) error {
	if message.ID == 0 || message.ID >= 0x4000 || message.Name == "" || message.GoName == "" || message.Revision == 0 {
		return fmt.Errorf("message %q has invalid identity or revision", message.Name)
	}
	if _, exists := streams[message.Stream]; !exists {
		return fmt.Errorf("message %s references unknown stream %q", message.Name, message.Stream)
	}
	if len(message.Fields) == 0 {
		return fmt.Errorf("message %s has no fields", message.Name)
	}
	optionalBits := make(map[uint8]string)
	fieldNames := make(map[string]struct{}, len(message.Fields))
	for _, field := range message.Fields {
		if err := validateField(message, field, optionalBits, fieldNames); err != nil {
			return err
		}
	}
	return nil
}

func validateField(message messageDefinition, field fieldDefinition, optionalBits map[uint8]string, fieldNames map[string]struct{}) error {
	if err := validateFieldIdentity(message, field, fieldNames); err != nil {
		return err
	}
	if err := validateFieldBounds(message, field); err != nil {
		return err
	}
	return validateOptionalField(message, field, optionalBits)
}

func validateFieldIdentity(message messageDefinition, field fieldDefinition, fieldNames map[string]struct{}) error {
	if field.Name == "" || field.GoName == "" || field.Trust == "" {
		return fmt.Errorf("message %s contains an incomplete field", message.Name)
	}
	if _, exists := fieldNames[field.Name]; exists {
		return fmt.Errorf("message %s repeats field %s", message.Name, field.Name)
	}
	fieldNames[field.Name] = struct{}{}
	return nil
}

func validateFieldBounds(message messageDefinition, field fieldDefinition) error {
	validType := oneOf(field.Type, "uint", "sint", fieldTypeBool, fieldTypeString, fieldTypeBytes, fieldTypeFixed16,
		fieldTypeOpaque32, fieldTypeStringList, fieldTypeBrowserList, fieldTypeApplicationUsageList)
	if !validType {
		return fmt.Errorf("message %s field %s has unknown type %q", message.Name, field.Name, field.Type)
	}
	if oneOf(field.Type, "uint", "sint", fieldTypeString, fieldTypeBytes) && field.Maximum == 0 {
		return fmt.Errorf("message %s field %s has no bound", message.Name, field.Name)
	}
	if field.Type == fieldTypeStringList && (field.CountMaximum <= 0 || field.ItemMaximum <= 0 || field.AggregateMaximum <= 0) {
		return fmt.Errorf("message %s field %s has incomplete list bounds", message.Name, field.Name)
	}
	return nil
}

func validateOptionalField(message messageDefinition, field fieldDefinition, optionalBits map[uint8]string) error {
	if field.OptionalBit == nil {
		return nil
	}
	if *field.OptionalBit >= message.PresenceBits {
		return fmt.Errorf("message %s field %s uses unassigned optional bit", message.Name, field.Name)
	}
	if previous, exists := optionalBits[*field.OptionalBit]; exists {
		return fmt.Errorf("message %s optional bit %d reused by %s and %s", message.Name, *field.OptionalBit, previous, field.Name)
	}
	optionalBits[*field.OptionalBit] = field.Name
	return nil
}

func generateRegistry(schema protocolSchema) ([]byte, error) {
	var output strings.Builder
	output.WriteString(generatedHeader)
	output.WriteString("\npackage wire\n\n")
	output.WriteString("// StreamInitiator identifies which authenticated peer may open a stream.\ntype StreamInitiator uint8\n\n")
	output.WriteString("const (\n\t// InitiatorAgent permits only the authenticated agent.\n\tInitiatorAgent StreamInitiator = iota + 1\n\t// InitiatorGateway permits only the gateway.\n\tInitiatorGateway\n\t// InitiatorEither permits either authenticated peer.\n\tInitiatorEither\n)\n\n")
	output.WriteString("// StreamDirection identifies the QUIC stream direction required by XBP.\ntype StreamDirection uint8\n\n")
	output.WriteString("const (\n\t// DirectionUnidirectional carries bytes from its initiator only.\n\tDirectionUnidirectional StreamDirection = iota + 1\n\t// DirectionBidirectional carries bytes in both directions.\n\tDirectionBidirectional\n)\n\n")
	output.WriteString("// StreamSpecification is the immutable topology and frame bound for a stream kind.\ntype StreamSpecification struct {\n\tName string\n\tMaximumFrameBytes uint32\n\tInitiator StreamInitiator\n\tDirection StreamDirection\n\tMandatory bool\n}\n\n")
	output.WriteString("// SpecificationForStream returns the reviewed XBP stream contract.\nfunc SpecificationForStream(kind StreamKind) (StreamSpecification, bool) {\n\tswitch kind {\n")
	for _, stream := range schema.Streams {
		fmt.Fprintf(&output, "\tcase Stream%s:\n\t\treturn StreamSpecification{Name: %q, MaximumFrameBytes: %d, Initiator: %s, Direction: %s, Mandatory: %t}, true\n", stream.GoName, stream.Name, stream.MaximumFrameBytes, initiatorConstant(stream.Initiator), directionConstant(stream.Direction), stream.Mandatory)
	}
	output.WriteString("\tdefault:\n\t\treturn StreamSpecification{}, false\n\t}\n}\n\n")
	output.WriteString("const (\n")
	for _, message := range schema.Messages {
		fmt.Fprintf(&output, "\t// Message%s identifies %s revision %d.\n\tMessage%s MessageType = %#x\n", message.GoName, message.Name, message.Revision, message.GoName, message.ID)
	}
	output.WriteString(")\n\n")
	output.WriteString("// MessageDescriptor describes one immutable registry assignment.\ntype MessageDescriptor struct {\n\tType MessageType\n\tName string\n\tStream StreamKind\n\tRevision uint8\n\tAcknowledgement string\n\tCommitPoint string\n\tRetryContract string\n}\n\n")
	output.WriteString("// DescriptorForMessage returns the immutable assignment for a message type.\nfunc DescriptorForMessage(messageType MessageType) (MessageDescriptor, bool) {\n\tswitch messageType {\n")
	for _, message := range schema.Messages {
		stream := findStream(schema.Streams, message.Stream)
		fmt.Fprintf(&output, "\tcase Message%s:\n\t\treturn MessageDescriptor{Type: Message%s, Name: %q, Stream: Stream%s, Revision: %d, Acknowledgement: %q, CommitPoint: %q, RetryContract: %q}, true\n", message.GoName, message.GoName, message.Name, stream.GoName, message.Revision, message.Acknowledgement, message.Commit, message.Retry)
	}
	output.WriteString("\tdefault:\n\t\treturn MessageDescriptor{}, false\n\t}\n}\n\n")
	output.WriteString("// ValidateMessageForStream rejects unassigned types, wrong lanes, and revisions.\nfunc ValidateMessageForStream(kind StreamKind, messageType MessageType, revision uint8) error {\n\tdescriptor, ok := DescriptorForMessage(messageType)\n\tif !ok || descriptor.Stream != kind || descriptor.Revision != revision {\n\t\treturn ErrUnexpectedMessage\n\t}\n\treturn nil\n}\n")
	return format.Source([]byte(output.String()))
}

func generateMessages(schema protocolSchema) ([]byte, error) {
	var output strings.Builder
	output.WriteString(generatedHeader)
	output.WriteString("\npackage wire\n\n")
	for _, message := range schema.Messages {
		fmt.Fprintf(&output, "// %s is the canonical revision %d body for Message%s.\ntype %s struct {\n", message.GoName, message.Revision, message.GoName, message.GoName)
		if message.PresenceBits > 0 {
			output.WriteString("\t// Presence selects assigned optional fields; unassigned bits are rejected.\n\tPresence uint64\n")
		}
		for _, field := range message.Fields {
			fmt.Fprintf(&output, "\t%s %s\n", field.GoName, goType(field.Type))
		}
		output.WriteString("}\n\n")
		fmt.Fprintf(&output, "// MarshalBinary returns the canonical bounded %s body.\nfunc (message %s) MarshalBinary() ([]byte, error) {\n\tbuilder := NewBuilder(256)\n", message.Name, message.GoName)
		if message.PresenceBits > 0 {
			fmt.Fprintf(&output, "\tbuilder.Presence(message.Presence, %d)\n", message.PresenceBits)
		}
		for _, field := range message.Fields {
			writeOptionalStart(&output, field, "message.Presence")
			fmt.Fprintf(&output, "\t%s\n", encodeStatement(field))
			writeOptionalEnd(&output, field)
		}
		output.WriteString("\treturn builder.Bytes()\n}\n\n")
		fmt.Fprintf(&output, "// UnmarshalBinary replaces the message with one exact canonical %s body.\nfunc (message *%s) UnmarshalBinary(body []byte) error {\n\tparser := NewParser(body)\n\tvar decoded %s\n", message.Name, message.GoName, message.GoName)
		if message.PresenceBits > 0 {
			fmt.Fprintf(&output, "\tdecoded.Presence = parser.Presence(%d)\n", message.PresenceBits)
		}
		for _, field := range message.Fields {
			writeOptionalStart(&output, field, "decoded.Presence")
			fmt.Fprintf(&output, "\t%s\n", decodeStatement(field))
			writeOptionalEnd(&output, field)
		}
		output.WriteString("\tif err := parser.Done(); err != nil {\n\t\treturn err\n\t}\n\t*message = decoded\n\treturn nil\n}\n\n")
	}
	return format.Source([]byte(output.String()))
}

func generateReference(schema protocolSchema) []byte {
	var output strings.Builder
	output.WriteString("<!-- Code generated by go run ./cmd/wiregen; DO NOT EDIT. -->\n\n")
	fmt.Fprintf(&output, "# %s v%d.%d Wire Reference\n\n", schema.Protocol.Name, schema.Protocol.Major, schema.Protocol.Minor)
	fmt.Fprintf(&output, "ALPN: `%s`. Integers use canonical unsigned LEB128 unless a field says otherwise. Optional fields are preceded by the message's canonical little-bit-order presence map.\n\n", schema.Protocol.ALPN)
	output.WriteString("## Streams\n\n| Code | Kind | Initiator | Direction | Maximum frame bytes | Mandatory |\n| ---: | --- | --- | --- | ---: | --- |\n")
	for _, stream := range schema.Streams {
		fmt.Fprintf(&output, "| `0x%02x` | %s | %s | %s | %d | %t |\n", stream.Code, stream.Name, stream.Initiator, stream.Direction, stream.MaximumFrameBytes, stream.Mandatory)
	}
	output.WriteString("\n## Messages\n")
	for _, message := range schema.Messages {
		fmt.Fprintf(&output, "\n### `%s` (`0x%04x`, revision %d)\n\nStream: `%s`. Acknowledgement: `%s`. Commit: `%s`. Retry: `%s`.\n\n| Order | Field | Encoding | Bound | Optional bit | Classification |\n| ---: | --- | --- | ---: | ---: | --- |\n", message.Name, message.ID, message.Revision, message.Stream, message.Acknowledgement, message.Commit, message.Retry)
		for index, field := range message.Fields {
			bound := fieldBound(field)
			optional := "required"
			if field.OptionalBit != nil {
				optional = strconv.Itoa(int(*field.OptionalBit))
			}
			fmt.Fprintf(&output, "| %d | `%s` | `%s` | %s | %s | %s |\n", index+1, field.Name, field.Type, bound, optional, field.Trust)
		}
	}
	return []byte(output.String())
}

func compareGenerated(file generatedFile) error {
	current, err := os.ReadFile(filepath.Clean(file.path))
	if err != nil {
		return fmt.Errorf("read generated file %s: %w", file.path, err)
	}
	if !bytes.Equal(current, file.data) {
		return fmt.Errorf("generated file %s is stale; run make wire-generate", file.path)
	}
	return nil
}

func oneOf(value string, allowed ...string) bool {
	for _, candidate := range allowed {
		if value == candidate {
			return true
		}
	}
	return false
}

func findStream(streams []streamDefinition, name string) streamDefinition {
	for _, stream := range streams {
		if stream.Name == name {
			return stream
		}
	}
	return streamDefinition{}
}

func initiatorConstant(value string) string {
	return map[string]string{"agent": "InitiatorAgent", "gateway": "InitiatorGateway", "either": "InitiatorEither"}[value]
}

func directionConstant(value string) string {
	return map[string]string{"unidirectional": "DirectionUnidirectional", "bidirectional": "DirectionBidirectional"}[value]
}

func goType(fieldType string) string {
	return map[string]string{
		"uint": "uint64", "sint": "int64", "bool": "bool", fieldTypeString: "string", fieldTypeBytes: "[]byte",
		fieldTypeFixed16: "[16]byte", fieldTypeOpaque32: "[32]byte", fieldTypeStringList: "[]string",
		fieldTypeBrowserList: "[]BrowserObservation", fieldTypeApplicationUsageList: "[]ApplicationUsage",
	}[fieldType]
}

func encodeStatement(field fieldDefinition) string {
	name := "message." + field.GoName
	if statement, exists := map[string]string{
		fieldTypeBool:                 "builder.Bool(" + name + ")",
		fieldTypeFixed16:              "builder.Fixed16(" + name + ")",
		fieldTypeOpaque32:             "builder.Opaque32(" + name + ")",
		fieldTypeBrowserList:          "appendBrowserObservations(builder, " + name + ")",
		fieldTypeApplicationUsageList: "appendApplicationUsage(builder, " + name + ")",
	}[field.Type]; exists {
		return statement
	}
	switch field.Type {
	case "uint":
		return fmt.Sprintf("builder.BoundedUint(%s, %d)", name, field.Maximum)
	case "sint":
		return fmt.Sprintf("builder.BoundedSInt(%s, %d)", name, field.Maximum)
	case fieldTypeString:
		return fmt.Sprintf("builder.String(%s, %d)", name, field.Maximum)
	case fieldTypeBytes:
		return fmt.Sprintf("builder.BytesField(%s, %d)", name, field.Maximum)
	case fieldTypeStringList:
		return fmt.Sprintf("builder.StringList(%s, %d, %d, %d)", name, field.CountMaximum, field.ItemMaximum, field.AggregateMaximum)
	default:
		return ""
	}
}

func decodeStatement(field fieldDefinition) string {
	name := "decoded." + field.GoName
	if statement, exists := map[string]string{
		fieldTypeBool:                 name + " = parser.Bool()",
		fieldTypeFixed16:              name + " = parser.Fixed16()",
		fieldTypeOpaque32:             name + " = parser.Opaque32()",
		fieldTypeBrowserList:          name + " = parseBrowserObservations(parser)",
		fieldTypeApplicationUsageList: name + " = parseApplicationUsage(parser)",
	}[field.Type]; exists {
		return statement
	}
	switch field.Type {
	case "uint":
		return fmt.Sprintf("%s = parser.Uint(%d)", name, field.Maximum)
	case "sint":
		return fmt.Sprintf("%s = parser.SInt(%d)", name, field.Maximum)
	case fieldTypeString:
		return fmt.Sprintf("%s = parser.String(%d)", name, field.Maximum)
	case fieldTypeBytes:
		return fmt.Sprintf("%s = parser.BytesField(%d)", name, field.Maximum)
	case fieldTypeStringList:
		return fmt.Sprintf("%s = parser.StringList(%d, %d, %d)", name, field.CountMaximum, field.ItemMaximum, field.AggregateMaximum)
	default:
		return ""
	}
}

func writeOptionalStart(output *strings.Builder, field fieldDefinition, presence string) {
	if field.OptionalBit != nil {
		fmt.Fprintf(output, "\tif %s&(uint64(1)<<%d) != 0 {\n\t", presence, *field.OptionalBit)
	}
}

func writeOptionalEnd(output *strings.Builder, field fieldDefinition) {
	if field.OptionalBit != nil {
		output.WriteString("\t}\n")
	}
}

func fieldBound(field fieldDefinition) string {
	switch field.Type {
	case "string_list":
		return fmt.Sprintf("count %d; item %d; aggregate %d", field.CountMaximum, field.ItemMaximum, field.AggregateMaximum)
	case "browser_list":
		return "32 entries; 64 KiB aggregate"
	case "application_usage_list":
		return "64 entries"
	case "fixed16":
		return "16 bytes"
	case "opaque32":
		return "32 bytes"
	case "bool":
		return "1 byte"
	default:
		return strconv.FormatUint(field.Maximum, 10)
	}
}
